#!/usr/bin/env python3
import os
import sys
import argparse
import kconfiglib

def parse_args():
    parser = argparse.ArgumentParser(description="NavHAL Kconfig to CMake and C Header generator")
    parser.add_argument("--kconfig", default="Kconfig", help="Path to Kconfig file")
    parser.add_argument("--config", default=".config", help="Path to .config file")
    parser.add_argument("--cmake-out", default=None, help="Path to output config.cmake")
    parser.add_argument("--header-out", default=None, help="Path to output autoconf.h")
    parser.add_argument("--navhal-target-out", default=None,
                        help="Path to output navhal_target.h "
                             "(NAVHAL_CONFIG_*/NAVHAL_HAS_*/target identity)")
    parser.add_argument("--board-header-out", default=None,
                        help="Path to output the generated board.h")
    parser.add_argument("--sample-override", default=None, help="Force sample activation by name")
    parser.add_argument("--menuconfig", action="store_true", help="Launch interactive menuconfig")
    return parser.parse_args()

def run_menuconfig(kconfig_file, config_file):
    try:
        from menuconfig import menuconfig
        
        os.environ["KCONFIG_CONFIG"] = config_file
        kh = kconfiglib.Kconfig(kconfig_file)
        menuconfig(kh)
        print("Configuration saved to", config_file)
    except ImportError:
        print("Error: 'kconfiglib' is required for interactive menuconfig.", file=sys.stderr)
        sys.exit(1)

def load_kconfig_proper(kconfig_path, config_path):
    """
    Uses official kconfiglib to evaluate Kconfig and automatically 
    propagate SELECT directives and dependencies properly.
    """
    try:
        # Tell kconfiglib which config file to use
        os.environ["KCONFIG_CONFIG"] = config_path
        kb = kconfiglib.Kconfig(kconfig_path, warn=False)
        
        # Try to load existing user config if present
        if os.path.exists(config_path):
            requested = _requested_bools(config_path)
            kb.load_config(config_path)
            print(f"Loaded user configuration from '{config_path}'")
            _report_dropped(kb, requested)
        else:
            print(f"Warning: No configuration file found at '{config_path}'. Using default settings.")

        # Re-evaluate and sync state back to .config just in case selections updated
        kb.write_config(config_path)

        return kb
    except ImportError:
        print("FATAL ERROR: Python module 'kconfiglib' is required. Please run: pip install kconfiglib", file=sys.stderr)
        sys.exit(1)

def _requested_bools(config_path):
    """The symbols a .config asked for with =y, by name."""
    asked = set()
    with open(config_path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("CONFIG_") and line.endswith("=y"):
                asked.add(line[len("CONFIG_"):-len("=y")])
    return asked


def _report_dropped(kb, requested):
    """Say which requested symbols this target cannot provide, and why.

    Kconfig drops an assignment whose dependencies are unmet, which is correct and
    silent. Silence is the problem: a .config asking for CONFIG_DRV_GPIO=y on a port
    with no GPIO backend used to fail the build on a missing port header, and once
    the dependency was declared it instead built quietly without GPIO. Neither tells
    the person what happened. Both are worse than a sentence.
    """
    dropped = []
    for name in sorted(requested):
        sym = kb.syms.get(name)
        if sym is None:
            continue
        if sym.str_value == "n":
            dep = kconfiglib.expr_str(sym.direct_dep)
            dropped.append((name, dep))
    if not dropped:
        return
    print("Warning: this target cannot provide what the configuration asked for:")
    for name, dep in dropped:
        print(f"  CONFIG_{name}=y ignored -- needs: {dep}")
    print("  (the build continues without them; see docs/capabilities/README.md)")


def generate_cmake(kconfig_obj, output_path):
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write("# Automatically generated by NavHAL Configuration Engine. DO NOT EDIT.\n")
        f.write("# NavHAL CMake Configuration File\n\n")
        
        # Loop through all symbols defined in the Kconfig
        for sym in kconfig_obj.unique_defined_syms:
            name = sym.name
            if not name:
                continue
                
            prefix_name = f"CONFIG_{name}"
            val = sym.str_value
            
            # Convert kconfiglib string output into valid CMake assignments
            if sym.type == kconfiglib.BOOL or sym.type == kconfiglib.TRISTATE:
                # 'y' / 'n' / 'm'
                c_val = "ON" if val == 'y' else "OFF"
                f.write(f"set({prefix_name} {c_val} CACHE INTERNAL \"\")\n")
            elif sym.type == kconfiglib.STRING:
                f.write(f"set({prefix_name} \"{val}\" CACHE INTERNAL \"\")\n")
            else:
                # Int/Hex
                f.write(f"set({prefix_name} {val} CACHE INTERNAL \"\")\n")
            
            # Unprefixed legacy bridges
            legacy = ["BOARD", "VENDOR", "FAMILY", "ARCH_ISA", "CMAKE_SYSTEM_PROCESSOR", "TOOLCHAIN_PREFIX", "USE_FPU", "STANDALONE", "SAMPLE", "TEST", "FLASHER", "FLASH_ADDRESS"]
            if name in legacy:
                if sym.type == kconfiglib.BOOL:
                     c_val = "ON" if val == 'y' else "OFF"
                     f.write(f"set({name} {c_val} CACHE INTERNAL \"\")\n")
                elif sym.type == kconfiglib.STRING:
                     f.write(f"set({name} \"{val}\" CACHE INTERNAL \"\")\n")
                else:
                     f.write(f"set({name} {val} CACHE INTERNAL \"\")\n")

def generate_header(kconfig_obj, output_path):
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    # Use built-in standard autoconf.h generator provided by kconfiglib!
    kconfig_obj.write_autoconf(output_path)

# Mapping from Kconfig symbol name → NAVHAL_HAS_<suffix>. The HAS_* names are
# the stable capability contract used by HAL headers (see hal_features.h);
# they may diverge from the underlying Kconfig spelling, so the map is
# explicit rather than derived.
NAVHAL_HAS_MAP = {
    "DRV_DMA":       "DMA",
    "USE_FPU":       "FPU",
    "DRV_CRC":       "CRC_HW",
    "DRV_DWT":       "CYCLE_COUNTER",
    "DRV_SDIO":      "SDIO",
    "DRV_GPIO":      "GPIO",
    "DRV_UART":      "UART",
    "DRV_I2C":       "I2C",
    "DRV_SPI":       "SPI",
    "DRV_TIMER":     "TIMER",
    "DRV_PWM":       "PWM",
    "DRV_CLOCK":     "CLOCK",
    "DRV_INTERRUPT": "INTERRUPT",
    "DRV_FLASH":     "FLASH",
    "DRV_MPU":       "MPU",
    "DRV_CACHE":     "CACHE",
    "USE_TCM":       "TCM",
    # Per-driver capability sub-options (WI4.4).
    "DRV_UART_DMA":  "UART_DMA",
    "DRV_I2C_DMA":   "I2C_DMA",
    "DRV_SDIO_DMA":  "SDIO_DMA",
}

def _sym_str(kb, name):
    """Look up a Kconfig string-valued symbol; return '' if not found."""
    for sym in kb.unique_defined_syms:
        if sym.name == name:
            return sym.str_value
    return ""

def _sym_y(kb, name):
    """1 if a Kconfig bool/tristate symbol is 'y', 0 otherwise."""
    for sym in kb.unique_defined_syms:
        if sym.name == name:
            return 1 if sym.str_value == "y" else 0
    return 0

# --- generated board.h -------------------------------------------------------

# Every board fact is a Kconfig symbol, and this turns them into the board.h that
# code includes. The header is generated rather than hand-written so there is one
# description of a board instead of two free to disagree -- which is what let the
# SDIO driver hardcode pins while board.h named the same pins in a comment, and
# let BOARD_SD_CD describe a real line that nothing read.
#
# Driven by symbol prefix rather than a table here, so adding a board fact is a
# Kconfig edit and nothing else:
#
#   PIN_<NAME>_PORT + PIN_<NAME>_PIN   ->  #define <NAME> HAL_GPIO_PIN(p, n)
#   NUM_<NAME>                         ->  #define <NAME> <int>
#   VAL_<NAME>                         ->  #define <NAME> <verbatim>
#
# VAL_ exists because not every board fact is a number. HAL_IRQ_USART_RX is the
# AVR console's interrupt and is not derivable from an instance number; LED_BUILTIN
# on a board whose only indicator is an RGB channel is an alias to another macro.
# Forcing those through integers would encode a lie, so they are strings and the
# generator emits them as written.

_PIN_PREFIX = "PIN_"
_NUM_PREFIX = "NUM_"
_VAL_PREFIX = "VAL_"


def _emit_define(f, name, value, comment=None):
    line = f"#define {name:<24} {value}"
    if comment:
        line += f" /* {comment} */"
    f.write(line + "\n")


def generate_board_header(kconfig_obj, output_path):
    """Emit board.h from the board's Kconfig values."""
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    board = _sym_str(kconfig_obj, "BOARD")

    pins, nums, vals = {}, {}, {}
    for sym in kconfig_obj.unique_defined_syms:
        if not sym.name:
            continue
        v = sym.str_value
        if v == "" or v == "n":
            continue
        if sym.name.startswith(_PIN_PREFIX):
            if sym.name.endswith("_PORT"):
                pins.setdefault(sym.name[len(_PIN_PREFIX):-5], {})["port"] = v
            elif sym.name.endswith("_PIN"):
                pins.setdefault(sym.name[len(_PIN_PREFIX):-4], {})["pin"] = v
        elif sym.name.startswith(_NUM_PREFIX):
            nums[sym.name[len(_NUM_PREFIX):]] = v
        elif sym.name.startswith(_VAL_PREFIX):
            vals[sym.name[len(_VAL_PREFIX):]] = v

    with open(output_path, "w") as f:
        f.write("/* Automatically generated by tools/kconfig.py. DO NOT EDIT. */\n")
        f.write(f"/* Board: {board}. Source: src/board/{board}/Kconfig + .config */\n")
        f.write("/* Change a value there, or override it in .config. */\n\n")
        f.write("#ifndef NAVHAL_BOARD_H\n#define NAVHAL_BOARD_H\n\n")
        # Not every port has every type header -- the x86-64 port has no GPIO at
        # all -- and which ones a board needs depends on what it describes. Guard
        # each, the way common/hal_config.h guards its own optional include.
        f.write("/* Type headers, as this port provides them. */\n")
        f.write("#if defined(__has_include)\n")
        for h in ("gpio", "uart", "spi", "i2c", "timer", "adc"):
            f.write(f'#  if __has_include("utils/{h}_types.h")\n')
            f.write(f'#    include "utils/{h}_types.h"\n')
            f.write("#  endif\n")
        f.write("#else\n")
        for h in ("gpio", "uart", "spi", "i2c", "timer", "adc"):
            f.write(f'#  include "utils/{h}_types.h"\n')
        f.write("#endif\n\n")

        if pins:
            f.write("/* ---- Pins ---- */\n")
            base = _sym_str(kconfig_obj, "GPIO_PORT_BASE") or "A"
            for name in sorted(pins):
                pp = pins[name]
                if "port" not in pp or "pin" not in pp:
                    continue
                letter = chr(ord(base) + int(pp["port"]))
                _emit_define(f, name, f'HAL_GPIO_PIN({pp["port"]}, {pp["pin"]})',
                             f'P{letter}{pp["pin"]}')
            f.write("\n")

        if nums:
            f.write("/* ---- Numbers ---- */\n")
            for name in sorted(nums):
                _emit_define(f, name, nums[name])
            f.write("\n")

        if vals:
            f.write("/* ---- Named values ---- */\n")
            for name in sorted(vals):
                _emit_define(f, name, vals[name])
            f.write("\n")

        f.write("#endif /* NAVHAL_BOARD_H */\n")


def generate_navhal_target_header(kconfig_obj, output_path):
    """Emit navhal_target.h with the stable NavHAL macros derived from Kconfig.

    Three sections:
      * Target identity   — NAVHAL_TARGET_{ARCH,VENDOR,BOARD} (string literals).
      * NAVHAL_CONFIG_*   — one macro per Kconfig symbol, mirroring autoconf.h
                            with a NAVHAL_ prefix and 0/1 instead of undefined.
                            This is the single source of truth guards key off
                            (force-included into every TU, Linux autoconf-style).
      * NAVHAL_HAS_*      — DEPRECATED thin aliases of the matching
                            NAVHAL_CONFIG_* macro, kept only so out-of-tree
                            consumers of the old capability contract keep
                            building. New code MUST use NAVHAL_CONFIG_DRV_*.
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("/* Automatically generated by tools/kconfig.py. DO NOT EDIT. */\n")
        f.write("/* Source: NavHAL Kconfig + .config */\n\n")
        f.write("#ifndef NAVHAL_TARGET_H\n")
        f.write("#define NAVHAL_TARGET_H\n\n")

        f.write("/* ===== Target identity ===== */\n")
        f.write(f'#define NAVHAL_TARGET_ARCH   "{_sym_str(kconfig_obj, "CMAKE_SYSTEM_PROCESSOR")}"\n')
        f.write(f'#define NAVHAL_TARGET_VENDOR "{_sym_str(kconfig_obj, "VENDOR")}"\n')
        f.write(f'#define NAVHAL_TARGET_FAMILY "{_sym_str(kconfig_obj, "FAMILY")}"\n')
        f.write(f'#define NAVHAL_TARGET_BOARD  "{_sym_str(kconfig_obj, "BOARD")}"\n\n')

        f.write("/* ===== Resolved Kconfig symbols (NAVHAL_CONFIG_*) ===== */\n")
        for sym in kconfig_obj.unique_defined_syms:
            if not sym.name:
                continue
            val = sym.str_value
            if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
                bv = 1 if val == "y" else 0
                f.write(f"#define NAVHAL_CONFIG_{sym.name} {bv}\n")
            elif sym.type == kconfiglib.STRING:
                f.write(f'#define NAVHAL_CONFIG_{sym.name} "{val}"\n')
            else:
                f.write(f"#define NAVHAL_CONFIG_{sym.name} {val}\n")

        f.write("\n/* ===== DEPRECATED capability aliases (NAVHAL_HAS_* -> NAVHAL_CONFIG_*) =====\n"
                " * Kept for backward compatibility only. Prefer NAVHAL_CONFIG_DRV_*.\n"
                " */\n")
        for kconfig_sym, has_suffix in NAVHAL_HAS_MAP.items():
            f.write(f"#define NAVHAL_HAS_{has_suffix} NAVHAL_CONFIG_{kconfig_sym}\n")

        f.write("\n#endif /* NAVHAL_TARGET_H */\n")

def main():
    args = parse_args()
    
    # 1. Handle menuconfig mode
    if args.menuconfig:
        run_menuconfig(args.kconfig, args.config)
        if not args.cmake_out and not args.header_out:
            return
    
    # 2. Handle standard code generation
    if not args.cmake_out and not args.header_out and not args.navhal_target_out \
            and not args.board_header_out:
        print("No output paths specified. Operation complete.")
        return
    
    # 3. Evaluated load using official lib - handles SELECT cascades automatically
    kb = load_kconfig_proper(args.kconfig, args.config)

    # 3.5 Apply direct sample override passed via CLI to cascade dependencies correctly
    if args.sample_override and args.sample_override.strip():
        sample_name = args.sample_override.strip().lower()
        
        # Locate the matching symbol by matching trailing path components
        # For sample "hal_dwt", we look for a config matching "SAMPLE_*HAL_DWT"
        matched = False
        for sym in kb.unique_defined_syms:
             if sym.name and sym.name.startswith("SAMPLE_"):
                  # Slug is "NN_<name>" (e.g. SAMPLE_11_HAL_I2C -> 11_hal_i2c).
                  slug = sym.name.replace("SAMPLE_", "", 1).lower()
                  # Strip the leading curriculum-number prefix, if present.
                  parts = slug.split("_", 1)
                  deslug = (parts[1] if len(parts) == 2 and parts[0].isdigit()
                            else slug)
                  # Exact match only — a substring test wrongly pairs
                  # "hal_i2c" with "no_hal_i2c" (and picks whichever the
                  # Kconfig lists first).
                  if sample_name == slug or sample_name == deslug:
                       sym.set_value('y')
                       print(f"Forcing activation of sample symbol: {sym.name}")
                       matched = True
                       break
        if not matched:
             print(f"Warning: No matching Kconfig symbol found for sample '{sample_name}'")
    
    # 4. Render Outputs
    if args.cmake_out:
        print(f"Generating CMake config to '{args.cmake_out}'...")
        generate_cmake(kb, args.cmake_out)
        
    if args.header_out:
        print(f"Generating C header to '{args.header_out}'...")
        generate_header(kb, args.header_out)

    if args.navhal_target_out:
        print(f"Generating navhal_target.h to '{args.navhal_target_out}'...")
        generate_navhal_target_header(kb, args.navhal_target_out)

    if args.board_header_out:
        print(f"Generating board.h to '{args.board_header_out}'...")
        generate_board_header(kb, args.board_header_out)

    print("KConfig verification and generation completed successfully!")

if __name__ == "__main__":
    main()
