#!/usr/bin/env python3
import os
import sys
import argparse

def parse_args():
    parser = argparse.ArgumentParser(description="NavHAL Kconfig to CMake and C Header generator")
    parser.add_argument("--kconfig", default="Kconfig", help="Path to Kconfig file")
    parser.add_argument("--config", default=".config", help="Path to .config file")
    parser.add_argument("--cmake-out", default=None, help="Path to output config.cmake")
    parser.add_argument("--header-out", default=None, help="Path to output autoconf.h")
    parser.add_argument("--menuconfig", action="store_true", help="Launch interactive menuconfig")
    return parser.parse_args()

def run_menuconfig(kconfig_file, config_file):
    try:
        import kconfiglib
        from menuconfig import menuconfig
        
        # Load the Kconfig definition
        os.environ["KCONFIG_CONFIG"] = config_file
        kh = kconfiglib.Kconfig(kconfig_file)
        
        # Open menuconfig
        menuconfig(kh)
        print("Configuration saved to", config_file)
    except ImportError:
        print("Error: 'kconfiglib' is required for interactive menuconfig.", file=sys.stderr)
        print("Please install it using: pip install kconfiglib windows-curses(on Windows)", file=sys.stderr)
        sys.exit(1)

def parse_config_file(config_file):
    """
    Parses a Kconfig format .config file.
    Returns a dictionary of key-value pairs representing configurations.
    """
    config = {}
    if not os.path.exists(config_file):
        print(f"Warning: Configuration file '{config_file}' not found. Using default empty configuration.")
        return config

    with open(config_file, 'r') as f:
        for line in f:
            line = line.strip()
            # Skip empty lines
            if not line:
                continue
            
            # Handle comments and disabled options
            if line.startswith('#'):
                # Handle standard Kconfig disabled syntax: "# CONFIG_FOO is not set"
                if line.startswith('# CONFIG_') and 'is not set' in line:
                    parts = line.split()
                    if len(parts) >= 3:
                        key = parts[1]
                        config[key] = ('bool', False)
                continue

            # Parse KEY=VALUE
            if '=' in line:
                key, val = line.split('=', 1)
                key = key.strip()
                val = val.strip()

                # Parse boolean
                if val == 'y':
                    config[key] = ('bool', True)
                elif val == 'n':
                    config[key] = ('bool', False)
                # Parse string
                elif val.startswith('"') and val.endswith('"'):
                    config[key] = ('string', val[1:-1])
                # Parse hex or integer
                else:
                    config[key] = ('number', val)

    return config

def write_cmake_config(config, output_path):
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write("# Automatically generated by tools/kconfig.py. DO NOT EDIT.\n")
        f.write("# NavHAL CMake Configuration File\n\n")
        
        for key, (val_type, val) in sorted(config.items()):
            # Handle standard variables without prepending CONFIG_ if desired,
            # but standard is to define them as they are named in .config
            if val_type == 'bool':
                cmake_val = "ON" if val else "OFF"
                f.write(f"set({key} {cmake_val} CACHE INTERNAL \"\")\n")
            elif val_type == 'string':
                f.write(f"set({key} \"{val}\" CACHE INTERNAL \"\")\n")
            else:
                f.write(f"set({key} {val} CACHE INTERNAL \"\")\n")
            
            # Support un-prefixed versions for core legacy CMake variables:
            # e.g., CONFIG_BOARD -> BOARD, CONFIG_VENDOR -> VENDOR
            legacy_keys = ["CONFIG_BOARD", "CONFIG_VENDOR", "CONFIG_CMAKE_SYSTEM_PROCESSOR", "CONFIG_USE_FPU", "CONFIG_STANDALONE", "CONFIG_SAMPLE", "CONFIG_TEST", "CONFIG_FLASHER", "CONFIG_FLASH_ADDRESS"]
            if key in legacy_keys:
                unprefixed = key.replace("CONFIG_", "")
                if val_type == 'bool':
                    cmake_val = "ON" if val else "OFF"
                    f.write(f"set({unprefixed} {cmake_val} CACHE INTERNAL \"\")\n")
                elif val_type == 'string':
                    f.write(f"set({unprefixed} \"{val}\" CACHE INTERNAL \"\")\n")
                else:
                    f.write(f"set({unprefixed} {val} CACHE INTERNAL \"\")\n")

def write_header_config(config, output_path):
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write("/* Automatically generated by tools/kconfig.py. DO NOT EDIT. */\n")
        f.write("#ifndef AUTOCONF_H\n")
        f.write("#define AUTOCONF_H\n\n")
        
        for key, (val_type, val) in sorted(config.items()):
            if val_type == 'bool':
                if val:
                    f.write(f"#define {key} 1\n")
                else:
                    f.write(f"/* #undef {key} */\n")
            elif val_type == 'string':
                f.write(f"#define {key} \"{val}\"\n")
            else:
                f.write(f"#define {key} {val}\n")
                
        f.write("\n#endif /* AUTOCONF_H */\n")

def main():
    args = parse_args()
    
    if args.menuconfig:
        run_menuconfig(args.kconfig, args.config)
        if not args.cmake_out and not args.header_out:
            return
    
    # Standard generation
    if not args.cmake_out and not args.header_out:
        print("No output paths specified, skipping file generation.")
        return

    print(f"Parsing configuration from '{args.config}'...")
    config = parse_config_file(args.config)
    
    if args.cmake_out:
        print(f"Generating CMake config to '{args.cmake_out}'...")
        write_cmake_config(config, args.cmake_out)
    
    if args.header_out:
        print(f"Generating C header to '{args.header_out}'...")
        write_header_config(config, args.header_out)
        print("Kconfig generation completed successfully!")

if __name__ == "__main__":
    main()
