#!/usr/bin/env python3
import os
import sys
import argparse
import kconfiglib

def parse_args():
    parser = argparse.ArgumentParser(description="NavHAL Kconfig to CMake and C Header generator")
    parser.add_argument("--kconfig", default="Kconfig", help="Path to Kconfig file")
    parser.add_argument("--config", default=".config", help="Path to .config file")
    parser.add_argument("--cmake-out", default=None, help="Path to output config.cmake")
    parser.add_argument("--header-out", default=None, help="Path to output autoconf.h")
    parser.add_argument("--sample-override", default=None, help="Force sample activation by name")
    parser.add_argument("--menuconfig", action="store_true", help="Launch interactive menuconfig")
    return parser.parse_args()

def run_menuconfig(kconfig_file, config_file):
    try:
        from menuconfig import menuconfig
        
        os.environ["KCONFIG_CONFIG"] = config_file
        kh = kconfiglib.Kconfig(kconfig_file)
        menuconfig(kh)
        print("Configuration saved to", config_file)
    except ImportError:
        print("Error: 'kconfiglib' is required for interactive menuconfig.", file=sys.stderr)
        sys.exit(1)

def load_kconfig_proper(kconfig_path, config_path):
    """
    Uses official kconfiglib to evaluate Kconfig and automatically 
    propagate SELECT directives and dependencies properly.
    """
    try:
        # Tell kconfiglib which config file to use
        os.environ["KCONFIG_CONFIG"] = config_path
        kb = kconfiglib.Kconfig(kconfig_path, warn=False)
        
        # Try to load existing user config if present
        if os.path.exists(config_path):
            kb.load_config(config_path)
            print(f"Loaded user configuration from '{config_path}'")
        else:
            print(f"Warning: No configuration file found at '{config_path}'. Using default settings.")

        # Re-evaluate and sync state back to .config just in case selections updated
        kb.write_config(config_path)

        return kb
    except ImportError:
        print("FATAL ERROR: Python module 'kconfiglib' is required. Please run: pip install kconfiglib", file=sys.stderr)
        sys.exit(1)

def generate_cmake(kconfig_obj, output_path):
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write("# Automatically generated by NavHAL Configuration Engine. DO NOT EDIT.\n")
        f.write("# NavHAL CMake Configuration File\n\n")
        
        # Loop through all symbols defined in the Kconfig
        for sym in kconfig_obj.unique_defined_syms:
            name = sym.name
            if not name:
                continue
                
            prefix_name = f"CONFIG_{name}"
            val = sym.str_value
            
            # Convert kconfiglib string output into valid CMake assignments
            if sym.type == kconfiglib.BOOL or sym.type == kconfiglib.TRISTATE:
                # 'y' / 'n' / 'm'
                c_val = "ON" if val == 'y' else "OFF"
                f.write(f"set({prefix_name} {c_val} CACHE INTERNAL \"\")\n")
            elif sym.type == kconfiglib.STRING:
                f.write(f"set({prefix_name} \"{val}\" CACHE INTERNAL \"\")\n")
            else:
                # Int/Hex
                f.write(f"set({prefix_name} {val} CACHE INTERNAL \"\")\n")
            
            # Unprefixed legacy bridges
            legacy = ["BOARD", "VENDOR", "CMAKE_SYSTEM_PROCESSOR", "USE_FPU", "STANDALONE", "SAMPLE", "TEST", "FLASHER", "FLASH_ADDRESS"]
            if name in legacy:
                if sym.type == kconfiglib.BOOL:
                     c_val = "ON" if val == 'y' else "OFF"
                     f.write(f"set({name} {c_val} CACHE INTERNAL \"\")\n")
                elif sym.type == kconfiglib.STRING:
                     f.write(f"set({name} \"{val}\" CACHE INTERNAL \"\")\n")
                else:
                     f.write(f"set({name} {val} CACHE INTERNAL \"\")\n")

def generate_header(kconfig_obj, output_path):
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    # Use built-in standard autoconf.h generator provided by kconfiglib!
    kconfig_obj.write_autoconf(output_path)

def main():
    args = parse_args()
    
    # 1. Handle menuconfig mode
    if args.menuconfig:
        run_menuconfig(args.kconfig, args.config)
        if not args.cmake_out and not args.header_out:
            return
    
    # 2. Handle standard code generation
    if not args.cmake_out and not args.header_out:
        print("No output paths specified. Operation complete.")
        return
    
    # 3. Evaluated load using official lib - handles SELECT cascades automatically
    kb = load_kconfig_proper(args.kconfig, args.config)

    # 3.5 Apply direct sample override passed via CLI to cascade dependencies correctly
    if args.sample_override and args.sample_override.strip():
        sample_name = args.sample_override.strip().lower()
        
        # Locate the matching symbol by matching trailing path components
        # For sample "hal_dwt", we look for a config matching "SAMPLE_*HAL_DWT"
        matched = False
        for sym in kb.unique_defined_syms:
             if sym.name and sym.name.startswith("SAMPLE_"):
                  # Extract basic slug (e.g., 26_hal_dwt -> hal_dwt)
                  slug = sym.name.replace("SAMPLE_", "").lower()
                  # Try exact match on symbol tail or full slug
                  if sample_name in slug or slug in sample_name:
                       sym.set_value('y')
                       print(f"Forcing activation of sample symbol: {sym.name}")
                       matched = True
                       break
        if not matched:
             print(f"Warning: No matching Kconfig symbol found for sample '{sample_name}'")
    
    # 4. Render Outputs
    if args.cmake_out:
        print(f"Generating CMake config to '{args.cmake_out}'...")
        generate_cmake(kb, args.cmake_out)
        
    if args.header_out:
        print(f"Generating C header to '{args.header_out}'...")
        generate_header(kb, args.header_out)
        print("KConfig verification and generation completed successfully!")

if __name__ == "__main__":
    main()
